<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "files_accounts".
 *
 * @property int $id
 * @property int $project_id
 * @property string $file_path
 * @property string $bank_file_path
 * @property int $status
 * @property int $total_records
 * @property int $updated_records
 * @property string $error_description
 * @property int $created_by
 * @property int $updated_by
 * @property int $created_at
 * @property int $updated_at
 */
class FilesAccounts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $file;
    public $bank_file;
    public static function tableName()
    {
        return 'files_accounts';
    }
    public function behaviors()
    {
        return [TimestampBehavior::className(),];

    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['file_path'], 'required'],
            [['status','type', 'total_records', 'updated_records', 'created_by', 'updated_by', 'created_at', 'updated_at','project_id'], 'integer'],
            [['error_description','bank_file_path'], 'string'],
            [['file_path'], 'string', 'max' => 100],
            [['file'],'file','extensions' => 'csv', 'checkExtensionByMimeType' => false]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file_path' => 'File Path',
            'project_id' => 'Project',
            'bank_file_path' => 'Bank Email File Path',
            'status' => 'Status',
            'total_records' => 'Total Records',
            'updated_records' => 'Updated Records',
            'error_description' => 'Error Description',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    public function beforeSave($insert)
   {
       if( parent::beforeSave($insert)) { // TODO: Change the autogenerated stubd$model->file_path->name;iue
           if ($this->isNewRecord) {
               //$this->status = '0';
               $this->created_by = isset($this->created_by) ? $this->created_by : Yii::$app->user->getId();
           } else {
               $this->updated_by = isset($this->updated_by) ? $this->updated_by : Yii::$app->user->getId();
           }
           return true;
       } else {
           return false;
       }
   }
}
