<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "project_files".
 *
 * @property int $id
 * @property int $project_id
 * @property string $file_path
 * @property int $amount
 * @property int $status
 * @property int $created_by
 * @property int $approved_by
 * @property int $created_at
 * @property int $approved_at
 * @property int $updated_at
 */
class ProjectFiles extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $file;
    public static function tableName()
    {
        return 'project_files';
    }
    public function behaviors()
    {
        return [TimestampBehavior::className(),];

    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status','amount', 'created_by', 'approved_by', 'created_at', 'approved_at','updated_at','project_id'], 'integer'],
            [['file_path'], 'string'],
            [['file_path'], 'string', 'max' => 100]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file_path' => 'File Path',
            'project_id' => 'Project',
            'status' => 'Status',
            'created_by' => 'Created By',
            'approved_by' => 'Updated By',
            'created_at' => 'Created At',
            'approved_at' => 'Updated At',
        ];
    }
    public function beforeSave($insert)
   {
       if( parent::beforeSave($insert)) { // TODO: Change the autogenerated stubd$model->file_path->name;iue
           if ($this->isNewRecord) {
               //$this->status = '0';
               $this->created_by = isset($this->created_by) ? $this->created_by : Yii::$app->user->getId();
           } else {
               $this->approved_at = isset($this->approved_at) ? $this->approved_at : Yii::$app->user->getId();
           }
           return true;
       } else {
           return false;
       }
   }
}
